search_space:
  beta1:
    _type: choice
    _value: [0.9, 0.99]
  beta2:
    _type: choice
    _value: [0.99, 0.999]
  lr:
    _type: loguniform
    _value: [0.0001, 0.1]
  lr_f:
    _type: loguniform
    _value: [0.0001, 0.1]
  jitter_scale_ratio:
    _type: uniform
    _value: [0, 2.0]
  jitter_ratio:
    _type: uniform
    _value: [0, 0.5]
  f_remove:
    _type: uniform
    _value: [0, 0.2]
  f_add:
    _type: uniform
    _value: [0, 0.2]
  max_seg:
    _type: randint
    _value: [5, 10]


experimentName: Ingenuity_Cup_CWRU

trial_command: python main_nni.py
trial_code_directory: .
trialGpuNumber: 1

trial_concurrency: 1
max_trial_number: 50
max_experiment_duration: "4h"

tuner:
  name: TPE
  class_args:
    optimize_mode: maximize

assessor:
  name: "Medianstop"

training_service:
  platform: local
  useActiveGpu: True
